import qs from "qs";

import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import Navigation from "../components/Navigation";
import Link from "next/link";
import Card from "../components/Card";
import { CategoryAttributes, ResponseMany } from "../types";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <h2>Categories</h2>
          <ul className={styles.CardList}>
            {["Армія", "Дитячий будинок", "Червоний Хрест"].map((item) => (
              <li key={item} className={styles["CardList-Item"]}>
                <Link href="#">
                  <a>
                    <Card title={item} />
                  </a>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async ({
  res,
  locale,
}) => {
  const categoriesQuery = qs.stringify({ locale });
  const categoriesRes = await fetch(
    `${process.env.API_BASE_URL}/categories?${categoriesQuery}`
  );
  const categories: ResponseMany<CategoryAttributes> =
    await categoriesRes.json();

  const slugToRedirect =
    locale === "uk"
      ? categories.data[0].attributes.slug
      : `${locale}/${categories.data[0].attributes.slug}`;

  res.statusCode = 302;
  res.setHeader("Location", `/${slugToRedirect}`);

  return { props: {} };
};
